class Generator:
    def __init__(self, name, power, hours):
        self.generator_name = name
        self.rated_power = power
        self.operating_hours = hours
    def total_energy(self):
        return self.rated_power * self.operating_hours
name = input("Enter Generator Name: ")
power = float(input("Enter Rated Power (in kW): "))
hours = float(input("Enter Operating Hours: "))
gen = Generator(name, power, hours)
print(f"Total Energy Generated by {gen.generator_name}: {gen.total_energy()} kWh")
